### ISSUE TITLE
Pod stuck at

### ISSUE THREAD

**Issue by rturk** [coreos/alb-ingress-controller#101]
Lock is held by alb-ingress-controller-1528035493-xp8tl and has not yet expired

**Comment by joshrosso** [comment]
@rturk, what version of the controller are you using?

I haven't seen this before, perhaps it's conflicting with another ingress controller you have deployed?

You may wish to visit [Setting Ingress Resource Scope](https://github.com/coreos/alb-ingress-controller/blob/master/docs/configuration.md#setting-ingress-resource-scope), to prevent it from conflicting.

**Comment by rturk** [comment]
@joshrosso tks I'm still struggling with this, it is tricky to debug. I'll check resources scope docs
