### ISSUE TITLE
Add support for new host-based routing features in AWS

### ISSUE THREAD

**Issue by joshrosso** [coreos/alb-ingress-controller#11]
We should expand our L7 routing support beyond paths (currently in #5) into hosts now that [AWS supports host-based routing](https://aws.amazon.com/blogs/aws/new-host-based-routing-support-for-aws-application-load-balancers).

**Comment by donaldguy** [comment]
With this it would be neat to have more control over ALB creation. $16.20 per Ingress per month is a pretty steep base price for some startup-types;  now that there is host-based routing and up to 75 rules per ALB it would be nice to be able to get full allocation per cost

(Obviously this complicates SSL, but like ... star certs I guess)

**Comment by Awk34** [comment]
I believe we can have as many as 75 hosts per ALB, which could be a huge cost savings. Do you guys have any plan of attack for this issue?

**Comment by pweiss82** [comment]
I am also available to help with this.

**Comment by joshrosso** [comment]
@donaldguy @Awk34 @pweiss82 : Thanks for the input and willingness to help.

This is certainly one of the most important features of this controller and I'd like to see it implemented as soon as possible.

When we first wrote this controller (before open sourcing it) host-based routing wasn't available in ALBs. Additionally, we weren't aware Amazon was releasing it when they did.

That said, I think we should consider a [non-formal] proposal, which concisely describes how we'd like to handle host-based routing. Then we can implement against it.

An example ingress-resource manifest and a description of how the controller should act upon it should suffice. Detailing considerations like the one in #73.

I might not get to writing this up until early next week, but if someone would like to take a stab at it sooner, I'm open to it.

**Comment by joshrosso** [comment]
Quick-n-dirty proposal up.
https://docs.google.com/document/d/1yrJU_6qmuF1KkDyIiQvIjZ5N1wZ2Svbfsp0f-dPApss/edit?usp=sharing

Please add comments!

/cc @bigkraig @donaldguy @Awk34 @pweiss82 @yawboateng

**Comment by johananl** [comment]
Hey @joshrosso. Thanks for raising this issue.
Is there any work currently being done on this? I'd love to see this functionality implemented and am willing to contribute.

**Comment by pweiss82** [comment]
We are really in need of this at my organization. Do you think putting up a bounty for this would speed along the implementation? I think GO is a stopper for us contributing much as we don't have that skill set in house.

**Comment by bigkraig** [comment]
A lot of work has been done on this in #183 incase you guys want to give it a try. It will require building new load balancers since it is now able to use a single ALB for the ingress resource.

**Comment by johananl** [comment]
Very cool @bigkraig, thanks for the update!
We will definitely take a look.

**Comment by tomhughesnice** [comment]
Thanks for the update @bigkraig.
Will I have to build from source to test?

**Comment by johananl** [comment]
@tomhughesnice - you can probably use a Docker image from https://quay.io/repository/coreos/alb-ingress-controller?tab=tags (right @bigkraig?).

**Comment by tomhughesnice** [comment]
Ok cool, I guess I can just use the latest tag.

**Comment by tomhughesnice** [comment]
Just been messing around with it using the latest tag. 

This is supposed to allow two separate Ingress resources to share the same the same ALB as long as the spec.rules.host is the same? So far not having any luck, it always creates a separate ALB for each. 
Do I have to reference the shared ALB by name in the ingress?  I checked the Google doc above and their was a proposed 'alb.ingress.kubernetes.io/alb' annotation. But that does not appear to work.

**Comment by bigkraig** [comment]
@tomhughesnice That part isn't implemented yet. This is the first step towards something like that. What this allows today is configuring host & path rules and the use of a single ALB for multiple ingress paths.

**Comment by joshrosso** [comment]
I think we can consider this ticket the MVP and since it's implemented i'll close the issue as part of 1.0 (https://github.com/coreos/alb-ingress-controller/pull/197).

For those of you who test it out, please let us know what limitations or issues you find in new tickets.
