### ISSUE TITLE
Route53 Service GetZoneID fails to find ZoneId for Hosted Zone

### ISSUE THREAD

**Issue by robertervin** [coreos/alb-ingress-controller#112]
I have both public and private hosted zone files for example.com in Route53. I can run `aws route53 list-hosted-zones-by-name --dns-name=example.com` locally, and retrieve the ZoneIds from the response. 

When I deploy an ingress the `alb-ingress-controller` spits out this though 
```
I0529 18:43:17.687678       1 log.go:48] [ALB-INGRESS] [prod-alb-ingress] [INFO]: Start ELBV2 (ALB) modification.
I0529 18:43:17.687700       1 log.go:48] [ALB-INGRESS] [prod-alb-ingress] [INFO]: Start ELBV2 tag modification.
I0529 18:43:17.710160       1 log.go:48] [ALB-INGRESS] [prod-alb-ingress] [INFO]: Completed ELBV2 tag modification. Tags are [{    Key: "Hostname",    Value: "example.com"  },{    Key: "IngressName",    Value: "alb-ingress"  },{    Key: "Namespace",    Value: "prod"  }].
I0529 18:43:17.710177       1 log.go:62] [ALB-INGRESS] [prod-alb-ingress] [ERROR]: Sync stopped due to error. Error: Route53 Resource record set flagged as unresolveable. Record: example.com
I0529 18:43:17.710184       1 controller.go:420] ingress backend successfully reloaded...
I0529 18:43:19.687677       1 log.go:62] [ALB-INGRESS] [prod-alb-ingress] [ERROR]: Unabled to locate ZoneId for example.com.
I0529 18:43:19.687726       1 log.go:62] [ALB-INGRESS] [prod-alb-ingress] [ERROR]: Sync stopped due to error. Error: Route53 Resource record set flagged as unresolveable. Record: example.com
```

Though I've never used Go before, I believe this may be caused by https://github.com/coreos/alb-ingress-controller/blob/master/awsutil/route53.go#L68. The `string.Split(hnFull, ".")` should split my domain into `["example", "com"]`, which has length 2. So it may simply never be executing the loop.

**Comment by MikaNikulin** [comment]
Hi! Did you find a solution for this? I have the same issue - although I'm using subdomain.example.com as a host. Or any possible ideas what could cause this?

**Comment by RobertErvin** [comment]
@MikaNikulin I have not. I recently realized I don't need alb-ingress-controller since I can do anything I want to with an single ELB and a set of ingress rules per microservice, with a single nginx ingress controller.

**Comment by bigkraig** [comment]
@MikaNikulin There is a small bug in https://github.com/kubernetes/ingress/pull/985 that once resolved we will be able to update the ingress resource in Kubernetes with the ALB hostname. Once that is the case you can use https://github.com/kubernetes-incubator/external-dns/ to manage DNS. We are planning to remove Route53 from this controller completely. Will that work for you?

**Comment by bigkraig** [comment]
Master now supports this, you should be able to use the external-dns controller.
