### ISSUE TITLE
CLUSTER_NAME must be 11 characters or less

### ISSUE THREAD

**Issue by davd33** [coreos/alb-ingress-controller#113]
I'm having this error on deploying alb-ingress-controller.

`main.go:40] CLUSTER_NAME must be 11 characters or less`

Why must I have less than 11 characters for my cluster's name?
Can I fix this somehow and make alb-ingress-controller work?

Thank you.

**Comment by RobertErvin** [comment]
@davd33 I had this issue when I set mine up as well. I just shortened the name. See https://github.com/coreos/alb-ingress-controller/issues/48 for an explanation

**Comment by davd33** [comment]
Thank you for your answer.
How did you change the name of your cluster?
