### ISSUE TITLE
Cluster name and Kops

### ISSUE THREAD

**Issue by davd33** [coreos/alb-ingress-controller#114]
ALB ingress controller does not work if my cluster's name has points in it:

> Error: ValidationError: The load balancer name 'p1.lt.cl-cef9a6cae1e748c' can only contain characters that are alphanumeric characters and hyphens(-)

BUT kops won't work if the cluster name isn't a fully-qualified DNS name:

- example with 'p-cl':

> Cluster Name must be a fully-qualified DNS name (e.g. --name=mycluster.myzone.com)

- example with 'CL1':

> Cluster Name must be a valid DNS name (e.g. --name=mycluster.myzone.com) errors: a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')

How should I do to make this work?

**Comment by WillemMali** [comment]
I'm trying to get this to work with `kops` as well, but I'm choking on this error:

```
CLUSTER_NAME must be 11 characters or less
```

My cluster's called "development.x.tld" so there's no way it's going to fit inside 11 characters...

**Comment by davd33** [comment]
For this, have a look [here](https://github.com/coreos/alb-ingress-controller/issues/113).
On AWS you can create private hosted zones with the name you want. So you can create for instance 'my.cl' or even shorter if you wish: a.b.

**Comment by mxpv** [comment]
Same problem. Using host names with `kops` is a common use case. How about adding `alb.ingress.kubernetes.io/load-balancer-name` ?

**Comment by joshrosso** [comment]
The `CLUSTER_NAME` being picked up is here: https://github.com/coreos/alb-ingress-controller/blob/master/examples/alb-ingress-controller.yaml#L55-L56

I'm just now noticing our example is > 11 characters. Is this actually an issue related to kops? Or are the defaults being used and it's exceeding the max?

**Comment by joshrosso** [comment]
Keep in mind this env var setup in the controller manifest is only used to name ALBs created by the controller. This way you can identify where an ALB came from.

**Comment by mxpv** [comment]
> I'm just now noticing our example is > 11 characters. Is this actually an issue related to kops? Or are the defaults being used and it's exceeding the max?

kops needs cluster name to be fully-qualified DNS name, which is not accepted by ALB. It's possible to bypass 11 char limit in kops with private hosted zones.

**Comment by bigkraig** [comment]
Unfortunately due to AWS naming requirements we cant allow . in CLUSTER_NAME. This doesn't have to be the same value as what Kops is using though, so feel free to choose something different.

**Comment by eugene-marchenko** [comment]
Hey!
I completely love your way of creating ALBs. Using it for current EKS cluster without any issues.
Are you planning to add support for kops clusters?
[Current](https://github.com/kubernetes/kops/tree/master/addons/kube-ingress-aws-controller) approach does not allow me to use already existing infrastructure(VPC and SG) in predictable way.
Thanks!
