### ISSUE TITLE
Re-using existing ALB.

### ISSUE THREAD

**Issue by BattleBeaver** [coreos/alb-ingress-controller#130]
Guys I'm sorry if I am posting my question in improper place, but:

I've got AWS ALB left after previous k8s setup. 
Can I somehow `re-use ALB and related Target Groups` and preserve their settings like Route 53 mappings and ssl certificates? Or it is possible only set up new ALB with `alb-ingress-controller` and then will need to set everything up again?

**Comment by tuannvm** [comment]
+1

**Comment by bigkraig** [comment]
Currently the controller must manage the ALB completely. Any changes made to the ALB would be seen as an undesired state and rolled back.
