### ISSUE TITLE
Don't try to recreate good existing ALBs on controller startup

### ISSUE THREAD

**Issue by justinclayton** [coreos/alb-ingress-controller#132]
Every time the controller starts up, it looks like it attempts to go through the create process for each ingress resource, rather than simply evaluating current state. When coupled with issue #33, this makes it very difficult to tell what's net-new vs existing on startup, among other things.

**Comment by danopia** [comment]
I've noticed this snippit during startup:

```
I0720 04:18:17.894570       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0720 04:18:18.023542       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 0 ingresses from existing AWS resources
```

I have a half-dozen ALBs already, so something about the existing ingress code is not seeing them

**Comment by roccozanni** [comment]
@danopia do you have a `-` in the value of the CLUSTER_NAME environment variable? I was experiencing the same issue and looking at the code I noticed this line here:

https://github.com/coreos/alb-ingress-controller/blob/master/awsutil/elbv2.go#L216

that fails if the value of "CLUSTER_NAME" have a `-` in it, because the split will return more than two elements

**Comment by danopia** [comment]
Yea, I do, I just found the same line while looking at something else and came here to report.

The split seems unnecessary though, it's only checking for the clusterName prefix, but `HasPrefix` already checked for `prefix+"-"`

**Comment by danopia** [comment]
Found a preexisting ticket: #98

I just write&deployed this patch to one of my clusters:

```patch
diff --git a/awsutil/elbv2.go b/awsutil/elbv2.go
index 5e889a0b..28dff4ac 100644
--- a/awsutil/elbv2.go
+++ b/awsutil/elbv2.go
@@ -225,11 +225,7 @@ func (e *ELBV2) DescribeLoadBalancers(clusterName *string) ([]*elbv2.LoadBalance
 
                for _, loadBalancer := range describeLoadBalancersOutput.LoadBalancers {
                        if strings.HasPrefix(*loadBalancer.LoadBalancerName, *clusterName+"-") {
-                               if s := strings.Split(*loadBalancer.LoadBalancerName, "-"); len(s) == 2 {
-                                       if s[0] == *clusterName {
-                                               loadbalancers = append(loadbalancers, loadBalancer)
-                                       }
-                               }
+                               loadbalancers = append(loadbalancers, loadBalancer)
                        }
                }
 ```

Seems to be working fine, picked up my ALBs at startup and only applied changes. Is it that simple?

**Comment by bigkraig** [comment]
It is using the `-` in the name to determine if the ALB is something managed by the cluster. Another option would be to pull back the tags for all ALBs at startup and look for the ClusterName tag.

The current solution is to disallow `-` in the cluster name.

**Comment by danopia** [comment]
My cluster name already has a `-` though. Changing cluster name will make all new ALBs, yes?
