### ISSUE TITLE
question: should 'status.loadBalancer.ingress' on ingress objects reflect the created ALBs?

### ISSUE THREAD

**Issue by matt-deboer** [coreos/alb-ingress-controller#149]
Is it expected that when the controller creates/associates ALBs with an ingress, that ingress' `status.loadBalancer` object should reflect this?

If not, is there any resource or metadata existing in kube where one can interrogate which load-balancers have been associated with a given ingress?

The reason I ask, is I am not currently seeing anything (i.e., `kubectl get ingress` shows empty 'Address' field, and `status.loadBalancer.ingress == {}`), and I'm looking to update route53 externally--but without some object reference to the ALB, this is pretty difficult...

**Comment by matt-deboer** [comment]
Added PR #150 to address this issue.

**Comment by joshrosso** [comment]
For ref (as noted in PR above), this is an essential change for running external-dns and getting us to our fully decoupled DNS / controller model.

We'll be pulling in the ingress code updates to allow for direct modification of this field.

**Comment by bigkraig** [comment]
Check out master, this is in there now :+1:
