### ISSUE TITLE
controller does not detect when it's ALBs are externally deleted

### ISSUE THREAD

**Issue by matt-deboer** [coreos/alb-ingress-controller#161]
Upon manually deleting one of the ALBs created by `alb-ingress-controller` (either via console or api call), I would expect the controller to recreate that missing ALB after some time. 

At the least, the controller should recognize that the ALB is missing; instead, the controller happily reports `ingress backend successfully reloaded...`.

A restart of the ingress controller causes it to resolve (and recreate) the deleted ALB.

**Comment by bigkraig** [comment]
:+1: I think a routine resync with AWS is in order.

**Comment by matt-deboer** [comment]
ok; PR coming up shortly..

**Comment by joshrosso** [comment]
Thanks for the PR @matt-deboer; going to take a look at getting this into our 1.0 PR today or tomorrow.

**Comment by joshrosso** [comment]
Added and tested.
