### ISSUE TITLE
Route53 record deletion issue

### ISSUE THREAD

**Issue by ledor473** [coreos/alb-ingress-controller#173]
# Issue
The Route53 record is still present after the Ingress is deleted.

The Ingress was annotated with:
```
kubernetes.io/ingress.class: alb
```

# Logs
```
I0810 15:59:21.613356       1 controller.go:187] ignoring delete for ingress redacted-ingress-name based on annotation kubernetes.io/ingress.class
```

# Version
quay.io/coreos/alb-ingress-controller:9ba180e2

**Comment by bigkraig** [comment]
Route53 management has been removed from the controller
