### ISSUE TITLE
alb.ingress.kubernetes.io/healthcheck-port doesn't work

### ISSUE THREAD

**Issue by philnalwalker** [coreos/alb-ingress-controller#174]
Trying to setup a simple test of the ALB ingress controller. No matter how I specify the healthcheck port it doesn't seem to work. 

I've tried:

alb.ingress.kubernetes.io/healthcheck-port: "30071"
alb.ingress.kubernetes.io/healthcheck-port: "default 30071"
alb.ingress.kubernetes.io/healthcheck-port: "override 30071"

to no avail. Am I missing something here?

**Comment by bigkraig** [comment]
what version are you running? this was added recently in https://github.com/coreos/alb-ingress-controller/commit/8a95a594cdd8c344c9b97c5c51d7aefffa5216a9

**Comment by philnalwalker** [comment]
I was running the 0.8 release. Switching to a newer build fixes this.
