### ISSUE TITLE
Mirror for China

### ISSUE THREAD

**Issue by lareeth** [coreos/alb-ingress-controller#176]
Connecting to quay.io from China is severely limited stopping this container for being pulled. Could you please upload to this a provider that has a Chinese mirror so this can be run in AWS China.

For instance DaoCloud and Aliyun both provide free mirrors of Docker Hub.

**Comment by joshrosso** [comment]
@lareeth Would you like to setup your own provider and point it to this repo to build the container? Being OSS, I don't see anything preventing that.

I don't see us maintaining a mirror at the moment.

**Comment by joshrosso** [comment]
Closing this for now. Please let us know if we can help further @lareeth
