### ISSUE TITLE
DISABLE_ROUTE53 env var is partially ignored with latest updates

### ISSUE THREAD

**Issue by matt-deboer** [coreos/alb-ingress-controller#178]
After some recent updates, it seems that the `DISABLE_ROUTE53` env var (with value of `true`) is parsed when first creating the controller, but afterward (when `ALBController.ConfigureFlags` is called), that value is overridden to false, resulting in `nil`/ memory access violations--because the route43 service was not created, but the code attempts to access it.

**Comment by bigkraig** [comment]
thanks!
