### ISSUE TITLE
Using CLUSTER_NAME values containing "-" causes failures to reconcile

### ISSUE THREAD

**Issue by matt-deboer** [coreos/alb-ingress-controller#181]
When the `cluster-name` config value contains the hyphen character, load-balancer reconciliation will never happen, do to the code below: (from `ELBV2.DescribeLoadBalancers`)

```
if strings.HasPrefix(*loadBalancer.LoadBalancerName, *clusterName+"-") {
  if s := strings.Split(*loadBalancer.LoadBalancerName, "-"); len(s) == 2 {
    if s[0] == *clusterName {
      loadbalancers = append(loadbalancers, loadBalancer)
    }
  }
}
```
An error should be thrown when `-` is used, or else it should be converted to something else, like `_` before being used in the loadbalancer name.

**Comment by bigkraig** [comment]
Fixed in master. thanks!
