### ISSUE TITLE
Controller creates one ALB per ingress resource.

### ISSUE THREAD

**Issue by tedostrem** [coreos/alb-ingress-controller#192]
I was expecting the controller to create one ALB for all of my ingress resources but apparently it's creating one ALB per ingress resource (That will become expensive quickly).

What is the expected behavior here?

I'm running the examples in this repository on a standard kops-generated kubernetes cluster on AWS.

Thank you.

EDIT: Even when specifying all the service rules in the same ingress, it creates one ALB per service.

**Comment by gregoryguillou** [comment]
It should be available starting with https://github.com/coreos/alb-ingress-controller/pull/183. If you are using an older release, it is for sure expected.

**Comment by tedostrem** [comment]
Thank you @gregoryguillou, I changed image tag to :latest and its working as expected now.
Might be worth updating examples to latest release tag or list the release tags in the readme.

That said, thanks a lot of this controller. It's very helpful for our websocket services.
