### ISSUE TITLE
quay.io/coreos/alb-ingress-controller-helm seems to be out of date

### ISSUE THREAD

**Issue by BlueMonday** [coreos/alb-ingress-controller#193]
The version of the helm chart in quay.io/coreos/alb-ingress-controller-helm seems to be old. There were some improvement/fixes made to the chart that are not present in the version available on quay.io.

It would be nice if the changes were propagated.

**Comment by BlueMonday** [comment]
@mgoodness

**Comment by mgoodness** [comment]
We're still working on the CI process that will push new versions of the chart to CoreOS's app registry on Quay. I hope to get it nailed down very soon.

In the meantime, my [personal registry](https://quay.io/application/mgoodness/alb-ingress-controller-helm) should have the latest build. Feel free to grab it from there.

**Comment by mgoodness** [comment]
The easiest way to resolve this is to allow the Quay user for pushing Docker images to also push Helm charts (https://github.com/coreos/alb-ingress-controller/blob/master/helm_push.sh). That'll have to be done by someone at CoreOS.

**Comment by khrisrichardson** [comment]
Permissions have been granted to allow the helm charts to be pushed. This can be closed now.
