### ISSUE TITLE
default-http-backend does not have any active endpoints.

### ISSUE THREAD

**Issue by tedostrem** [coreos/alb-ingress-controller#195]
Using :latest tag of the alb-ingress-controller, everything works fine but when I log the ingress controller it keeps showing the following message every n seconds.
```
W0904 08:15:31.005988       1 controller.go:585] service kube-system/default-http-backend does not have any active endpoints
W0904 08:15:31.006291       1 controller.go:585] service kube-system/default-http-backend does not have any active endpoints
W0904 08:15:31.006313       1 controller.go:585] service kube-system/default-http-backend does not have any active endpoints
W0904 08:15:31.006328       1 controller.go:585] service kube-system/default-http-backend does not have any active endpoints
I0904 08:15:31.006628       1 controller.go:423] backend reload required
I0904 08:15:31.007243       1 controller.go:432] ingress backend successfully reloaded...
```
I would like to resolve this because it does not seem sane to have to "reload the ingress backend" every n seconds.

**Comment by joshrosso** [comment]
Hi @tedostrem 

The backend reloads your seeing are from the kubernetes/ingress library itself detecting changes.  Many times these changes are a no-op for us, like in the case you posted above. Essentially a call to OnUpdate was made, but no work was done in the controller (or else you'd see additional logs.

Let me know if looking at https://github.com/kubernetes/ingress/blob/master/core/pkg/ingress/controller/controller.go#L477-L486 clears this up at all.
