### ISSUE TITLE
Controller does not apply all health check parameters

### ISSUE THREAD

**Issue by olitheolix** [coreos/alb-ingress-controller#199]
Hi,

I noticed that only some health check parameters will be applied to my target groups.

As an example, these will be applied correctly
```
   alb.ingress.kubernetes.io/healthcheck-path: '/core/healthcheck'
   alb.ingress.kubernetes.io/successCodes: '200,400,401'
```

whereas these have no effect 
```
   alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
   alb.ingress.kubernetes.io/healthy-threshold-count: '3'
   alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '6'
   alb.ingress.kubernetes.io/healthcheck-interval-seconds: '29'
```

I am on v0.8

**Comment by joshrosso** [comment]
@olitheolix we're currently doing a lot of work to bring this controller up to speed. `0.8` is quite old, is there a chance you could try the image version `b30d8d28` and let me know how that goes?

If it still doesn't work, i'll attempt to roll it up into https://github.com/coreos/alb-ingress-controller/pull/197

**Comment by olitheolix** [comment]
Switched to `quay.io/coreos/alb-ingress-controller:b30d8d28` and used my original ingress definition.

The health check parameters are now correct and the ALB works.

However, I do not get a Route53 entry anymore. The ingress controller log shows no errors. Incidentally, it also does not show any API requests for Route53 (I see all the other ones, eg for the ALB and target groups).

**Comment by joshrosso** [comment]
Hi @olitheolix,

Good to hear. We've removed route53 sync altogether from the controller in favor of using a project like https://github.com/kubernetes-incubator/external-dns to handle your route53 sync.

Soon we'll be documenting this process in respect to the controller. Until then, you'll want to use their docs to set up external-dns in your cluster.

I'll close this issue for now.

**Comment by olitheolix** [comment]
Thank you.
