### ISSUE TITLE
Route53 entries

### ISSUE THREAD

**Issue by yawboateng** [coreos/alb-ingress-controller#202]
Im running image: 93578098
with env:
```
 - name: DISABLE_ROUTE53
    value: "false"
```

however the route53 entries are not being created or logged. I know there was plans to isolate the route53 integration from this project a while back. is that the case now?

**Comment by joshrosso** [comment]
Hi @yawboateng, with https://github.com/coreos/alb-ingress-controller/commit/4d9c01c7817462476e20e6a241b5b48434bba751

Route53 integration was removed altogether in favor of using a separate project capable of syncing such as https://github.com/kubernetes-incubator/external-dns.

If you'd like to stay at the most current commit that has they syncing functionality still in it, try `5cb5491b`.

Let me know if this works for you. Docs on the way regarding how to go forward with the newest controller. Progress at https://github.com/coreos/alb-ingress-controller/pull/197.

**Comment by yawboateng** [comment]
Thanks for the info @joshrosso
