### ISSUE TITLE
Respect ingress lock held by (other) controller

### ISSUE THREAD

**Issue by joshrosso** [coreos/alb-ingress-controller#203]
Based on log observation, I believe we are not respecting the ingress lock today. As seen below.

```
Failed to update lock: Operation cannot be fulfilled on configmaps "ingress-controller-leader-alb": the object has been modified; please apply your changes to the latest version and try again
```

We should look into this and make sure we're not letting a second deployment of the controller stomp over another.

**Comment by aledbf** [comment]
@joshrosso this is fixed in master of kubernetes/ingress here https://github.com/kubernetes/ingress/pull/1338

**Comment by joshrosso** [comment]
@aledbf Thanks. Will upgrade ingress library and test.

**Comment by joshrosso** [comment]
Ingress library updated and no longer seeing issue in logs.
