### ISSUE TITLE
Targetgroups no longer update when changes to nodelist occur

### ISSUE THREAD

**Issue by joshrosso** [coreos/alb-ingress-controller#204]
Seems to be a regression somewhere in our host-based-routing work.

Previous PR: https://github.com/coreos/alb-ingress-controller/pull/57

Now, when I scale the worker pool, I never see the new node(s) added to the ALB's target groups.

**Comment by joshrosso** [comment]
AFAICT, when nodes deregister from k8s, the targetgroup is updated correctly.

However, when nodes are added, it's not reflected in the targetgroup.

**Comment by joshrosso** [comment]
After further investigation it seems `OnUpdate` is not being called when a new node registers. However, when a new node leaves the cluster the `OnUpdate` callback does fire. 

@aledbf does that sound at all possible?

Regardless, perhaps we should have some form a timer that calls OnUpdate on an interval ensuring ingress resources are being synced.

**Comment by aledbf** [comment]
> After further investigation it seems OnUpdate is not being called when a new node registers. However, when a new node leaves the cluster the OnUpdate callback does fire.

There is no event handler for nodes in the generic controller.
https://github.com/kubernetes/ingress/blob/master/core/pkg/ingress/controller/controller.go#L337

> However, when a new node leaves the cluster the OnUpdate callback does fire.

This could happen only if the node was running at least one endpoint referenced by an ingress rule

**Comment by joshrosso** [comment]
@aledbf Makes sense, thanks for the insight.

**Comment by joshrosso** [comment]
Implemented in https://github.com/coreos/alb-ingress-controller/commit/53e2f8bf375a9d190cccd3312b8c4d2186d26780
