### ISSUE TITLE
NLB - support - a topic here?

### ISSUE THREAD

**Issue by pmoosh** [coreos/alb-ingress-controller#205]
It is my understanding that NLB and ALB use the same (similar) API for configuration.

Is NLB support a topic here?

**Comment by joshrosso** [comment]
@pmoosh Yeah, as far as I understand, with targetgroups, the API is quite similar.

However, based on discussion in sig-aws, it seems there's intention to replace the native ELB integration with the NLB. 

In fact I believe @micahhausler is working on it so perhaps he can provide some context.

If we find a need (or someone makes the case) for including the NLB provision in the ALB controller, i'm open to it.

**Comment by pmoosh** [comment]
@joshrosso - thanks for your rapid reply.

Do you have a pointer to ongoing discussion at aws-sig?

Replacing/Adding the NLB to the native (classic) ELB integration seems a lot of work.
I glazed over the changes a bit an it seems that the main differentiator is the [LoadBalancerType](https://github.com/aws/aws-sdk-go/blob/4f310cca669fdd58021a326194742bbe61b4da10/models/apis/elasticloadbalancingv2/2015-12-01/api-2.json#L1269), which I don't think you guys set as you rely on the default setting. Although I haven't where you would define the optional EIP for the NLB. I am a go beginner, so I am trying to make sense of the code :-)

again thanks

**Comment by joshrosso** [comment]
@pmoosh : no problem.

I'm not certain how much work it would be regarding the default Loadbalancer integration (haven't looked into the code myself).

The GitHub issue is https://github.com/kubernetes/kubernetes/issues/52173.

Hope this helps.

**Comment by micahhausler** [comment]
Hi all, 

On the sig-aws call on Friday, it sounded to me like the intent is to add support for (but not replace) NLB's. I've been working on kubernetes/kubernetes#52173, and have made good progress, however the API requires more calls for an NLB than a classic ELB, but its totally doable.

As noted in previous comments, the API for NLB is very similar to ALB, but I don't think that NLB would work that well for an k8s ingress controller. K8s ingress controllers route based on paths and hostnames, so ALB is a great natural fit. The only thing you can do with NLB is route TCP traffic, so any ingress rules that specify hostnames or paths would be kind of useless.

**Comment by micahhausler** [comment]
One more thought: an NLB would work very well paired with an in-cluster ingress-controller, as the source-IP would be preserved all the way to the ingress controller. 

Right now in order to preserve the source IP, you have to turn on PROXY protocol on the ELB and your ingress controller has to support PROXY protocol.

**Comment by pmoosh** [comment]
@micahhausler - In my use case  source IP preservation and Static IP Addresses are the reasons to use NLB.

**Comment by joshrosso** [comment]
Agree with all the comments made by @micahhausler above. NLB integrated (as on option rather than replacement) for k8s-aws Loadbalancer integration is likely to be better for the community as a whole rather than rolling it into this controller.

Whether to use ALB -> nodeports -> pods or NLB -> ingress controller -> pods will really come down to an architectural preference.

**Comment by pmoosh** [comment]
Sounds good to me.

**Comment by Passpes** [comment]
Is the NLB supported already here? 
I find NLB really useful here as API Gateway is a service that lives outside the VPC; it is completely hosted and maintained in an AWS owned VPC, and its underlying infrastructure is invisible. API Gateway uses AWS PrivateLink technology to connect to the private resources. **PrivateLink publishes services based on Network Load Balancers**. As such, **API Gateway can only connect to the private resources through an internal NLB.** In the API Gateway console, you can create a VPC Link pointing to this NLB. The VPC Link can be used in your API Gateway definitions.

**Comment by M00nF1sh** [comment]
@Passpes 
Hi, the NLB support is built into k8s, you can add annotation ```service.beta.kubernetes.io/aws-load-balancer-type: "nlb"``` to your service, which will provision an nlb instead of default elb.

**Comment by Passpes** [comment]
Actually I know that annotation but in my case we need multiple target groups for different services and alb-ingress-controller supports that but misses the NLB, would be great to include it as it’s helpful for Microservices architechture linked with API gateway and VPC link.

**Comment by M00nF1sh** [comment]
@Passpes 
Hi, actually we have thought of build an ingress controller based on API gateway and NLB as well.
Would you help share us the gaps between APIGateway and ALB that make this architecture?
Currently, i'm only aware the rate limiting feature.

**Comment by Passpes** [comment]
Well basically API gateway supports some good security features and authentication for example with cognito and also a great API to call multipe AWS resources at the same time and link them together, so on of these resources are the microservices leaving on k8s therefore we need to link API gateway to those microservices -> the only way to do that is using NLB as explained, I think first step you can help implement NLB annotation as it’s supported by kubernetes already if possible soonish and later maybe adding API gateway from there.
