### ISSUE TITLE
Add support to determine SGs and Network IDs based on name tag

### ISSUE THREAD

**Issue by jescarri** [coreos/alb-ingress-controller#21]
People should be able to opt in for subnet and security group auto discovery.

```    
   alb.ingress.kubernetes.io/subnets: subnet1, subnet2
    alb.ingress.kubernetes.io/security-groups: sg1, sg2
```

**Comment by bigkraig** [comment]
The code to support this was already in there, did you test it out and find a bug?

**Comment by joshrosso** [comment]
I haven't tested it since we introduce the ability to explicitly call out a subnet ID.

@jescarri, can you validate the newest ALB build retains this functionality.

If it does, we'll need [a docs update here](https://github.com/coreos/alb-ingress-controller/blob/master/docs/ingress-resources.md#required-annotations) and we can close this.

**Comment by joshrosso** [comment]
Update on this, as I did a quick validation.

Subnets by tags still works, but causes subnet modification to loop. Likely how we're diffing current and desired subnet state (ids vs tags)

```
I0413 17:28:42.923381       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start ELBV2 (ALB) modification.
I0413 17:28:42.923513       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start subnets modification.
I0413 17:28:49.657713       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start ELBV2 (ALB) modification.
I0413 17:28:49.657816       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start subnets modification.
I0413 17:28:59.758839       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start ELBV2 (ALB) modification.
I0413 17:28:59.758874       1 log.go:48] [ALB-INGRESS] [echoserver-echoserver] [INFO]: Start subnets modification.
```

Security groups don't seem to work for me either. I did a name tag which should have resolved 3 security groups and it only resolved 1.

So in short, i'd say both of these need to be resolved / implemented.

I'm putting a small doc fix in to demonstrate our intentions and then I'll get around to implementing / fixing the functionality.

**Comment by joshrosso** [comment]
4bda6d34b93a5715c468cdbbbbdfa20454af508a

**Comment by joshrosso** [comment]
Update on this, it does in fact resolve via tags, but when taking the tag route and using multiple subnets, the desired subnets drop off somewhere causing the diff loop.

```
[ALB-INGRESS] [controller] [INFO]: Subnet found during parsing. subnet-c327adaa
[ALB-INGRESS] [controller] [INFO]: Subnet found during parsing. subnet-63bf6318
[ALB-INGRESS] [controller] [INFO]: currentSubnets: ["subnet-63bf6318","subnet-c327adaa"]
[ALB-INGRESS] [controller] [INFO]: desiredSubnets: ["subnet-63bf6318"]
```

Should be resolved shortly.
