### ISSUE TITLE
Federation support?

### ISSUE THREAD

**Issue by therc** [coreos/alb-ingress-controller#22]
I know that ALB is not GCLB and does not support cross-region forwarding, but could federation be supported at least

1) between clusters in the same region, which is useful when you're trying to shift traffic between them, e.g. when you don't want to switch to etcd3 in place
2) at the Route 53 level, with the assumption that all services in the ingress are replicated in all regions?

It doesn't look like there's any support or, if there is any, it's very well hidden.

**Comment by bigkraig** [comment]
You're right, there isn't any support yet.

I think this would be a pretty nice thing to be able to support though. As federation advances and tighten up loose ends in this controller its something I would like to have.

**Comment by joshrosso** [comment]
Let's reopen this ticket when federation in k8s becomes a more battle tested option.
