### ISSUE TITLE
Ingress backend info is hardcoded

### ISSUE THREAD

**Issue by fullsailor** [coreos/alb-ingress-controller#221]
Most importantly the version is always "1.0.0 git-00000000", which will make you wonder if you _really_ upgraded to 1.0.0-alpha.2

**Comment by joshrosso** [comment]
Thanks, will knock this out shortly.

**Comment by joshrosso** [comment]
Moving this into 1.1 for a longer term (automated fix) for now we'll update this manually for cuts.

**Comment by joshrosso** [comment]
Resolved by @bigkraig in https://github.com/coreos/alb-ingress-controller/pull/268
