### ISSUE TITLE
Bug: controller fails to start if CLUSTER_NAME > 11 chars

### ISSUE THREAD

**Issue by julianvmodesto** [coreos/alb-ingress-controller#223]
The controller fails to start if CLUSTERNAME > 11 chars.

```
$ kubectl --namespace=kube-system logs alb-ingress-controller-1788697744-rvnbf
I0925 16:13:21.159257       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
F0925 16:13:21.159340       1 main.go:40] CLUSTER_NAME must be 11 characters or less
```

This is pretty short. I'd like to use a cluster name like `prod.us-central-1`, but this is too long.

**Comment by julianvmodesto** [comment]
CLUSTERNAME also should be alphanumeric w/ hyphens only due to this error:

```
alb-ingress-controller-811629891-x1jgb server I0925 17:37:28.714187       1 log.go:62] [ALB-INGRESS] [default-frontend-alb] [ERROR]: Failed to create ELBV2 (ALB). Error: ValidationError: The load balancer name 'prod.use1-aebb3f5776e72e2' can only contain characters that are alphanumeric characters and hyphens(-)
```

**Comment by julianvmodesto** [comment]
Hmm I actually understand CLUSTER_NAME better now. Closing this.

**Comment by julianvmodesto** [comment]
Sorry re-opening -- my new ask here is if we could also ensure CLUSTER_NAME is alphanumeric only, so that the above loadbalancer naming doesn't error.

**Comment by whithajess** [comment]
The default name for a Kubernetes cluster created by https://github.com/kubernetes/kops is the DNS of the cluster so given I am from new zealand `.co.nz` (6 characters only 5 left) and if I try rename in **kops**:

 ```Ruby
Cluster Name must be a fully-qualified DNS name (e.g. --name=mycluster.myzone.com)
```

This pretty much means anyone using kops cannot use this `alb-ingress-controller` unless they happen to have mini domain names.

**Comment by whithajess** [comment]
Ah nvm seems it doesn't matter if it doesn't match the name of my cluster.

**Comment by julianvmodesto** [comment]
^^^ that's what I thought too, maybe it could be clearer in the docs

**Comment by whithajess** [comment]
Hmm im starting to think it does matter in AWS Kops will assign security groups like `nodes.example.com` and so far I haven't been able to get this to work and it seems like it hasn't added the rule to allow through those security groups to the NodePort.

**Comment by whithajess** [comment]
Either that or this controller just doesn't deal with opening up NodePorts and I didn't find anything about that in documentation.

**Comment by joshrosso** [comment]
@julianvmodesto work around this was completed as part of https://github.com/coreos/alb-ingress-controller/pull/197

Specifically https://github.com/coreos/alb-ingress-controller/commit/918d034df4f3994ca34f5d70d3de81f74d55e934 related to https://github.com/coreos/alb-ingress-controller/issues/198.

Could you try the image `501862ea` and let us know if the issue persists. If it's no longer a problem,  this will be part of the 1.0 release.

**Comment by julianvmodesto** [comment]
Thanks @joshrosso!

**Comment by joshrosso** [comment]
np! If it persists re-open this or a new ticket describing what different behavior you're seeing.
