### ISSUE TITLE
Build Instructions Not Working

### ISSUE THREAD

**Issue by alexmbird** [coreos/alb-ingress-controller#233]
I'm trying to follow the instructions in the `continued_stabilization` branch to get my own build of the latest code.

```
mock@MockAir12 ~/C/G/c/c/alb-ingress-controller> git branch
* continued_stabilization
...

mock@MockAir12 ~/C/G/c/c/alb-ingress-controller> glide install -v
...does stuff

mock@MockAir12 ~/C/G/c/c/alb-ingress-controller> go build
can't load package: package .: no Go files in [path removed]/code/contrib/alb-ingress-controller
```

Attempts to build from the Dockerfile fail in a different way:

```
mock@MockAir12 ~/C/G/c/c/alb-ingress-controller> docker build -t alb-ingress-controller .
Sending build context to Docker daemon  395.5MB
Step 1/4 : FROM alpine:3.5
 ---> 37c7be7a096b
Step 2/4 : RUN apk add --no-cache ca-certificates
 ---> Using cache
 ---> d59f1a77d826
Step 3/4 : COPY server server
COPY failed: stat /var/lib/docker/tmp/docker-builder961811684/server: no such file or directory
```

Am I doing something dumb here?  Given the project is evolving fast I'd like a surefire way to run the latest version.

**Comment by joshrosso** [comment]
Hi @alexmbird 

PTAL at https://github.com/coreos/alb-ingress-controller/pull/235
Specifically https://github.com/coreos/alb-ingress-controller/blob/update_build_instructions/BUILDING.md and let me know if that's more clear.

**Comment by alexmbird** [comment]
Perfect, just what I needed.  Thanks!
