### ISSUE TITLE
Different hosts as rules of instead of different ALBs

### ISSUE THREAD

**Issue by y86** [coreos/alb-ingress-controller#234]
Right now if I have two hosts on the specs of my ingress resource, one ALB is created for each one.

Could we have an option so that different hosts are configured as different rules of just one ALB?

**Comment by joshrosso** [comment]
@y86 - what version of the controller are you using?

**Comment by y86** [comment]
I am using this one:
quay.io/coreos/alb-ingress-controller:0.8

**Comment by joshrosso** [comment]
@y86 makes sense, that version does **not** support host-based-routing.

We just recently cut a version `1.0-alpha.3`. Would you be willing to give this a try? It includes the host-based-routing support you're looking for.

Do note it no longer syncs route53 natively. 

I'd recommend you checkout the walkthrough here: https://github.com/coreos/alb-ingress-controller/blob/master/docs/walkthrough.md

Please re-open this ticket or create a new one if this issue were to persist in the controller version that supports this feature.

**Comment by y86** [comment]
I'll give it a try and let you know.
Thanks @joshrosso!
