### ISSUE TITLE
"Failed to find related managed instance SG. Was it deleted from AWS" error

### ISSUE THREAD

**Issue by emas80** [coreos/alb-ingress-controller#236]
Hi, I am getting this error every couple of minutes.
I don't know exactly what caused this, the last thing we did was adding two annotations to the ingress to test the ssl redirect ( "ingress.kubernetes.io/ssl-redirect": "true" - I don't know if it would work or not, we were just testing it).
I already applied the previous configuration, but we keep having that error and there is no going back apparently.
It already happened before, and deleting the ALB from AWS fixed it - the new ALB was created automatically and everything was fine again.

I enabled the debug logs and I am also printing the AWS calls, it seems it's trying to describe the security group of the ALB, it's also printing the Security Group id. 
The security group is there, it was not deleted.

I "fixed" the error message, it was not printing the "err" object.
The complete error message is "Found more than 1 matching (managed) instance SGs. Found 2". 
(I will open a PR with the fix to print the error)

**Comment by emas80** [comment]
I fixed the issue our side, it was related to a wrong configuration of the security groups: while testing we have added a rule allowing access to our instances security group from the ALB security group, and this was causing the filter inside of the "DescribeSGByPermissionGroup" function to return 2 security groups instead of just one.

**Comment by joshrosso** [comment]
Thanks for the work @emas80!

**Comment by fr-sgujrati** [comment]
I am having the same error. I added a rule to allow my IP address to ssh into a node's instance. I removed that rule, but this error doesn't seem to go away. Any idea?
