### ISSUE TITLE
External-DNS not creating a record for hostname

### ISSUE THREAD

**Issue by garunski** [coreos/alb-ingress-controller#249]
When deploying the example echoservice, external-dns does not trigger to create the hostname. 

The load balancer is created correctly and when I use the loadbalancer dns name from AWS, the application works correctly. 

When I looked at the logs for external-dns:
`time="2017-10-19T21:28:49Z" level=debug msg="No endpoints could be generated from ingress default/postbackserver" `

When I check the alb-ingress-controller logs, I see this running in a 3 minute loop:
```I1019 21:36:13.509689       1 alb-controller.go:106] [ALB-INGRESS] [controller] [DEBUG]: Forcing ingress update as update hasn't occured in 3 minutes.
I1019 21:36:13.509936       1 loadbalancer.go:193] [ALB-INGRESS] [default/postbackserver] [DEBUG]: No modification of ELBV2 (ALB) required.
I1019 21:36:13.509960       1 targetgroup.go:176] [ALB-INGRESS] [default/postbackserver] [DEBUG]: No TargetGroup modification required.
I1019 21:36:13.509968       1 listener.go:112] [ALB-INGRESS] [default/postbackserver] [DEBUG]: No listener modification required.
I1019 21:36:13.509980       1 rule.go:137] [ALB-INGRESS] [default/postbackserver] [DEBUG]: No listener modification required.
I1019 21:36:13.510000       1 rule.go:113] [ALB-INGRESS] [default/postbackserver] [DEBUG]: Found desired rule that is a default and is already created with its respective listener. Rule: {  Actions: [{      Type: "forward"    }],  IsDefault: true,  Priority: "default"}
I1019 21:36:26.224074       1 albingress.go:307] [ALB-INGRESS] [default/postbackserver] [DEBUG]: Ingress library requested hostname list and we returned k--redacted-name---.us-east-1.elb.amazonaws.com
I1019 21:36:26.224096       1 status.go:337] updating Ingress default/postbackserver status to [{ k--redacted-name---.us-east-1.elb.amazonaws.com}]
I1019 21:36:26.230356       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"postbackserver", UID:"a4ac2912-b50e-11e7-9c2a-025797596f41", APIVersion:"extensions", ResourceVersion:"291608", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/postbackserver
I1019 21:36:26.273367       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"postbackserver", UID:"a4ac2912-b50e-11e7-9c2a-025797596f41", APIVersion:"extensions", ResourceVersion:"291611", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/postbackserver
I1019 21:36:56.228461       1 albingress.go:307] [ALB-INGRESS] [default/postbackserver] [DEBUG]: Ingress library requested hostname list and we returned k--redacted-name---.us-east-1.elb.amazonaws.com
I1019 21:36:56.228483       1 status.go:337] updating Ingress default/postbackserver status to [{ k--redacted-name---.us-east-1.elb.amazonaws.com}]
I1019 21:36:56.234461       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"postbackserver", UID:"a4ac2912-b50e-11e7-9c2a-025797596f41", APIVersion:"extensions", ResourceVersion:"291659", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/postbackserver
I1019 21:36:56.707016       1 event.go:218] Event(v1.ObjectReference{Kind:"Ingress", Namespace:"default", Name:"postbackserver", UID:"a4ac2912-b50e-11e7-9c2a-025797596f41", APIVersion:"extensions", ResourceVersion:"291662", FieldPath:""}): type: 'Normal' reason: 'UPDATE' Ingress default/postbackserver
```

When I checked the ingress yaml through the kubernetes ui, it had the Status.Loadbalancer as empty.
External-dns checks the hostname from that object, I don't know of another way to check the Status property of the Ingress so maybe I am looking at the wrong place. 
In either case it seems like the Status.LoadBalancer property on the ingress is not being set in my case and I am not sure how I can get a more detailed reason for the failure.

Thanks!

**Comment by whithajess** [comment]
Maybe verify with a different version of `external-dns` the current example is https://raw.githubusercontent.com/coreos/alb-ingress-controller/master/examples/external-dns.yaml which is `v0.4.2`

**Comment by garunski** [comment]
No changes when I run v0.4.2. Same log statement occurs 
`time="2017-10-19T23:25:03Z" level=debug msg="No endpoints could be generated from ingress default/postbackserver" `
And no dns entries were added to Route53.

**Comment by whithajess** [comment]
Did you follow the external-dns Deployment setup guide here:

https://github.com/coreos/alb-ingress-controller/blob/master/docs/setup.md

It includes the permissions you need.

**Comment by whithajess** [comment]
Have just tested with:

```ruby
external-dns: v0.4.7
alb-ingress-controller: 1.0-alpha.3
kubernetes: 1.8.0
```

All worked fine, I am assuming you are missing AWS permissions. Also I would suggest `:latest` may not be the best its not a tagged release so could have problems its just current `master`.

**Comment by garunski** [comment]
I have followed the guide mentioned. I also tried several different versions alb with no success. If i change the Service.Type to be LoadBalancer, the default aws elb is created and External-DNS creates the right A record to point to the newly created balancer. I think the permissions on AWS are correct. 
Could the issue be RBAC not configured properly? 
Do you see a repeating log entry about `status.go:337] updating Ingress` in your test?

**Comment by garunski** [comment]
Some new developments. It seems like waiting has been the answer. The changes did happen but they were 2 hours later. I am currently playing with the TTL seconds to see if that perhaps caused the delay.

**Comment by joshrosso** [comment]
@garunski - May I close this out? It seems more on the external-dns side than the controller (which is only responsible for reporting the hostname).

**Comment by garunski** [comment]
Yes. I could not figure out what caused the delay. If anyone else runs into this, for us the answer was wait.
