### ISSUE TITLE
Changing alb.ingress.kubernetes.io/certificate-arn doesn't apply changes in ALB

### ISSUE THREAD

**Issue by ese** [coreos/alb-ingress-controller#256]
If you want to change the certificate by changing `alb.ingress.kubernetes.io/certificate-arn` it has no effect in the ALB and its continue using the old one

version: 1.0-alpha3

**Comment by whithajess** [comment]
`1.0-alpha5` worked for me.

**Comment by joshrosso** [comment]
@ese Feel free to re-open if this doesn't update in 1.0-alpha5.

**Comment by toddams** [comment]
I'm confused, in readme it points that alpha3 is the latest, isn't it?
