### ISSUE TITLE
How to integrate Kubernetes with existing AWS ALB?

### ISSUE THREAD

**Issue by ramanSpandey** [coreos/alb-ingress-controller#306]
I want to use existing AWS ALB for my kubernetes setup. i.e. I don't want alb-ingress-controller create or update any existing AWS resource ie. Target groups, roles etc.

How can I make ALB to communicate with Kubernetes cluster, henceforth passing the request to existing services and getting the response back to ALB to display in the front end?

I tried alb-ingress-controller but it will create new ALB for new ingress resource. I want to use the existing ALB resource for it.

**Comment by bigkraig** [comment]
This controller is designed to manage the configuration of an ALB, it's not possible to merge ingress resources into existing ALBs.

There has been discussion around creating a single ALB or re-using ALBs for multiple ingresses inside of a cluster and I expect that to happen, but not leveraging an unmanaged ALB.
