### ISSUE TITLE
ARN does not exist

### ISSUE THREAD

**Issue by lee5i3** [coreos/alb-ingress-controller#358]
I am having an issue where it keeps saying "type: 'Warning' reason: 'ERROR' Error parsing annotations: ACM certificate ARN does not exist. ARN: arn:aws:acm:us-east-1:<my cert arn>"

I've check permissions, spelling.. region, still nothing..

After looking at the code (keep in mind, i am not a golang developer), shouldn't this be reversed? Not Equal instead of Equal?

https://github.com/coreos/alb-ingress-controller/blob/178cbf78f6dca4b46680d782b68e8427d78983c7/pkg/annotations/validation.go#L52-L57

**Comment by lee5i3** [comment]
Nevermind, fixed itself.. honestly not sure how, just happened to work

**Comment by EthanChouTW** [comment]
should this be reopened? fall into this issue +1,
can see the cert on AWS GUI console in load balancer but not passing validation on cli
ps: I'm using Cloud9
