### ISSUE TITLE
Invalid set idle timeout provided - doesnt say this is required?

### ISSUE THREAD

**Issue by natefox** [coreos/alb-ingress-controller#361]
I'm getting this error in the logs on container tagged 245bb34 (which is also `latest` as of this writing):
```
{"log":"E0409 17:18:52.886110       1 loadbalancer.go:362] [ALB-INGRESS] [demo/demo-ing] [ERROR]: Failed ELBV2 (ALB) tag modification: Invalid set idle timeout provided. Must be within 1-3600 seconds. No modification will be attempted. Was: 0\n","stream":"stderr","time":"2018-04-09T17:18:52.886418113Z"}
{"log":"E0409 17:18:52.886131       1 albingress.go:328] [ALB-INGRESS] [demo/demo-ing] [ERROR]: Failed to reconcile state on this ingress\n","stream":"stderr","time":"2018-04-09T17:18:52.88643863Z"}
{"log":"E0409 17:18:52.886139       1 albingress.go:330] [ALB-INGRESS] [demo/demo-ing] [ERROR]:  - Invalid set idle timeout provided. Must be within 1-3600 seconds. No modification will be attempted. Was: 0\n","stream":"stderr","time":"2018-04-09T17:18:52.886441849Z"}
{"log":"I0409 17:18:52.886153       1 controller.go:486] ingress backend successfully reloaded...\n","stream":"stderr","time":"2018-04-09T17:18:52.886444829Z"}
{"log":"I0409 17:18:52.886251       1 event.go:218] Event(v1.ObjectReference{Kind:\"Ingress\", Namespace:\"demo\", Name:\"demo-ing\", UID:\"62de8c29-3c11-11e8-9287-0a227d945858\", APIVersion:\"extensions\", ResourceVersion:\"3463114\", FieldPath:\"\"}): type: 'Warning' reason: 'ERROR' sandbox-demo-demoing-6442 tag modification failed: Invalid set idle timeout provided. Must be within 1-3600 seconds. No modification will be attempted. Was: 0\n","stream":"stderr","time":"2018-04-09T17:18:52.886447584Z"}
```

According to docs/ingress-resources.md the `alb.ingress.kubernetes.io/connection-idle-timeout` annotation is optional. Guessing this should have a default?

**Comment by gaganapplatix** [comment]
Yeah, I am also seeing this. And the ALB that gets created defaults to 60 seconds. The code says 



	if lb.DesiredIdleTimeout != nil {
		if err := albelbv2.ELBV2svc.SetIdleTimeout(lb.Current.LoadBalancerArn, *lb.DesiredIdleTimeout); err != nil {
			rOpts.Eventf(api.EventTypeWarning, "ERROR", "%s tag modification failed: %s", *lb.Current.LoadBalancerName, err.Error())
			lb.logger.Errorf("Failed ELBV2 (ALB) tag modification: %s", err.Error())
			return err
}

But DesiredIdleTimeout is a pointer and SetIdleTimeout doesn't like 0 value. so below fixes this I for me. I will submit a PR once I have stuff fully running for me 

diff --git a/pkg/alb/loadbalancer/loadbalancer.go b/pkg/alb/loadbalancer/loadbalancer.go
index b4ce8bed..c81de63a 100644
--- a/pkg/alb/loadbalancer/loadbalancer.go
+++ b/pkg/alb/loadbalancer/loadbalancer.go
@@ -370,7 +370,7 @@ func (lb *LoadBalancer) create(rOpts *ReconcileOptions) error {
 
        // DesiredIdleTimeout is 0 when no annotation was set, thus no modification should be attempted
        // this will result in using the AWS default
-       if lb.DesiredIdleTimeout != nil {
+       if lb.DesiredIdleTimeout != nil && *lb.DesiredIdleTimeout > 0 {
                if err := albelbv2.ELBV2svc.SetIdleTimeout(lb.Current.LoadBalancerArn, *lb.DesiredIdleTimeout); err != nil {
                        rOpts.Eventf(api.EventTypeWarning, "ERROR", "%s tag modification failed: %s", *lb.Current.LoadBalancerName, err.Error())
                        lb.logger.Errorf("Failed ELBV2 (ALB) tag modification: %s", err.Error())

**Comment by bigkraig** [comment]
Thanks for the fix!
