### ISSUE TITLE
Examples do not include `kubernetes.io/ingress.class` anotation

### ISSUE THREAD

**Issue by BlueMonday** [coreos/alb-ingress-controller#369]
[The helm values.yaml file by default limits the controller to the alb ingress class](https://github.com/coreos/alb-ingress-controller/blob/master/alb-ingress-controller-helm/values.yaml#L103). The examples however don't include the `kubernetes.io/ingress.class` annotation. This means that if a user installs alb-ingress-controller using the vanilla values.yaml file and tries one of the examples, the example wont work. This makes for a frustrating experience. The logs don't even make it obvious that the issue is the missing anotation. 

The examples I am referring to are these:
* https://github.com/coreos/alb-ingress-controller/blob/master/docs/ingress-resources.md#ingress-behavior
* https://github.com/coreos/alb-ingress-controller/blob/master/examples/2048/2048-ingress.yaml
* https://github.com/coreos/alb-ingress-controller/blob/master/examples/echoservice/echoserver-ingress.yaml

**Comment by tyrannasaurusbanks** [comment]
Cheers for spotting, I've updated the examples you found and had a quick look but couldn't see any others:
https://github.com/coreos/alb-ingress-controller/pull/372
