### ISSUE TITLE
Add option to ignore Host headers

### ISSUE THREAD

**Issue by riccardofreixo** [coreos/alb-ingress-controller#371]
At the moment if a hostname is specified the listeners get created with a Host header check rule, which forces users of the ALB to send that Host header. The logic is [here](https://github.com/coreos/alb-ingress-controller/blob/01441fa138e7255aa8632b9c9a7147baf47deb03/pkg/alb/rule/rule.go#L56):

```golang
if o.Hostname != "" {
	r.Conditions = append(r.Conditions, &elbv2.RuleCondition{
		Field:  aws.String("host-header"),
		Values: []*string{aws.String(o.Hostname)},
	})
}
```

That impedes using a higher level load balancer on top of the ALB, as the expected host would point to the ALB itself, and the higher load balancer would have a different hostname.

As we're using an NLB on top of the ALB, for supporting VPC Endpoints (aka PrivateLinks), and [external-dns](https://github.com/kubernetes-incubator/external-dns) to create all required hostnames, this blocks our use case.

My proposal is to add an annotation to allow ignoring the Host header check, e.g.:

`alb.ingress.kubernetes.io/ignore-host-header`

**Comment by bigkraig** [comment]
@riccardofreixo sounds good to me. thanks!

**Comment by riccardofreixo** [comment]
Made an early PR to iron out any kinks, but I'm still working on doing a full test on a kube cluster.
