### ISSUE TITLE
Instances are not added/removed from Target Group after it is created

### ISSUE THREAD

**Issue by jkemp101** [coreos/alb-ingress-controller#383]
It looks like something broke between version `1.0-alpha.8` and `67c350d` with target groups getting updated when the available nodes change.  I also tried the latest version `ac36437` and got the same result.  I happened to realize only 1 instance was in the target group even though the cluster had 3 nodes.

With `1.0-alpha.8` I get the following when I increased the instances in the ASG. The target group is modified as expected.
```
I0516 14:26:09.435104       1 loadbalancer.go:194] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: No modification of ELBV2 (ALB) required.
I0516 14:26:09.435136       1 targetgroup.go:323] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: Targets need to be changed.
I0516 14:26:09.435143       1 targetgroup.go:159] [ALB-INGRESS] [test/nginx-ingress] [INFO]: Start TargetGroup modification.
I0516 14:26:09.435155       1 targetgroup.go:323] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: Targets need to be changed.
I0516 14:26:09.649060       1 targetgroup.go:164] [ALB-INGRESS] [test/nginx-ingress] [INFO]: Succeeded TargetGroup modification. ARN: arn:aws:elasticloadbalancing:us-west-2:892789744163:targetgroup/test9k8susw-32596-HTTP-1cd5e8a/3145cca7dfe7b97b | Name: test9k8susw-32596-HTTP-1cd5e8a.
I0516 14:26:09.649093       1 listener.go:112] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: No listener modification required.
```

But with `67c350d` I get the following when I increase the ASG instance count:
```
I0516 14:22:30.140538       1 loadbalancer.go:703] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: test9k8susw-test-nginxingr-7831 checking if WAF needs update (old: <nil>, new: <nil>)
I0516 14:22:30.140550       1 loadbalancer.go:217] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: No modification of ELBV2 (ALB) required.
I0516 14:22:30.140567       1 targetgroup.go:169] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: No TargetGroup modification required.
I0516 14:22:30.140587       1 listener.go:112] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: No listener modification required.
I0516 14:22:30.140599       1 rule.go:141] [ALB-INGRESS] [test/nginx-ingress] [DEBUG]: No listener modification required.
```

**Comment by jkemp101** [comment]
@khrisrichardson I think PR #288 might have caused this regression.  Setting `tg.Targets.Desired = desired` versus what it was before basically `tg.Targets.Desired = targetGroup.Targets.Desired = o.GetNodes()` makes it so that new instances are never added to existing target groups.  I think it only ever removes instances from a target group and never adds new.

**Comment by khrisrichardson** [comment]
@jkemp101 I think there may be something squirrelly about this commit. I will take a closer look, but the determination of `desired` looks more reasonable than the determination of `current`.
