### ISSUE TITLE
Cluster width changes dont reflect in ALB Target Group

### ISSUE THREAD

**Issue by tavispaquette** [coreos/alb-ingress-controller#41]
Using the Cluster Autoscaler (https://github.com/kubernetes/contrib/blob/master/cluster-autoscaler/cloudprovider/aws/README.md) as more worker nodes are added or removed from the cluster we dont see the list of nodes being updated in the ALB target group

**Comment by joshrosso** [comment]
@tavispaquette, Yes we need to implement 'node list change awareness' asap.

Thanks for filing. it'll be worked on soon.

**Comment by joshrosso** [comment]
Hi @tavispaquette,

This should be fixed as of #57.

Could you verify using `quay.io/coreos/alb-ingress-controller:f9766433` and let me know? Thanks in advanced!

**Comment by joshrosso** [comment]
Closing this issue as we haven't seen any problems since implementing it.

Please feel free to reopen / comment if issues persist.

Thanks again!
