### ISSUE TITLE
CLUSTER_NAME character length

### ISSUE THREAD

**Issue by imacube** [coreos/alb-ingress-controller#48]
This is limited to 11 characters in main.go, is that limit still needed? 

The original function this appears to be related to from commit be873671797b1bc2183bb465f9fcc1d38c9679090 no longer exists.

`pkg/cmd/controller/elbv2.go`
```go
// Returns the ALBs name; maintains consistency amongst areas of code that much resolve this.
func (a *albIngress) Name() string {
	return fmt.Sprintf("%s-%s", a.clusterName, xid.New().String())
}
```

**Comment by joshrosso** [comment]
We still use `CLUSTER_NAME` when [creating the ALB](https://github.com/coreos/alb-ingress-controller/blob/ea86c5883ca9ab3b511ab1e094ae071c2d799bcc/controller/alb/loadbalancer.go#L52).

As you can see in the above link, the hash it's composed of can be 15 characters, the cluster name 11 and +1 for the hyphen, putting us at 27 characters.

The naming rules for AWS ALBs are: `Load balancer names cannot be longer than 32 characters`

Today, we do still have room to expand that limit, but still need to ensure it is within the bound of AWS's ALB creation rules. Or we could rethink it altogether and consider where to truncate.

**Comment by imacube** [comment]
Okay, that all makes sense. Thanks for the explanation!
