### ISSUE TITLE
Create an end-to-end example for echoservice

### ISSUE THREAD

**Issue by joshrosso** [coreos/alb-ingress-controller#56]
## Story

Those looking to try out the ALB-Ingress-Controller would likely benefit from an end-to-end example. Echo service seems like a good candidate. Let's write up an end-to-end example with the following criteria.

- Generate ALB for echoserver
- Show how logging works and how to understand what's happening
- Include multiple listeners
- Include HTTPS on 1 listener
- Show how modifications are handled

**Comment by nitrogenice** [comment]
Hi, I tried out using the controller last week, and had a bit of trouble trying to figure out how to configure an ALB that uses AWS certificates to listen on HTTPS. People like me would definitely benefit from some documentation. Thanks!
