### ISSUE TITLE
Create security group if annotation is not provided

### ISSUE THREAD

**Issue by mgoodness** [coreos/alb-ingress-controller#6]
If `alb.ingress.kubernetes.io/security-groups` is not specified, we should create an appropriate security group. This would mirror the behavior of Service type: LoadBalancer on AWS.

**Comment by tavispaquette** [comment]
+1

**Comment by justinclayton** [comment]
Other ingress controllers have established a pattern of using a ConfigMap for global defaults. [Here is an example of how the nginx controller does it](https://github.com/nginxinc/kubernetes-ingress/blob/master/examples/customization/README.md#using-configmaps). I'd love it if this project followed this pattern.

**Comment by greg-jaunt** [comment]
Beyond just creating the security group, the alb-ingress-controller needs to assign the security group to the instance nodes.

**Comment by joshrosso** [comment]
I'm going to add this to 1.0, it'll make our examples easier.

**Comment by joshrosso** [comment]
Added, docs coming soon as part of #197
