### ISSUE TITLE
Panic upon failing to describe hostedzones

### ISSUE THREAD

**Issue by bchav** [coreos/alb-ingress-controller#61]
Despite the IAM role on my controllers having the necessary Route53 permissions, it looks like the controller is failing to ListHostedZoneByName (need to dig into this a bit more)

I0417 21:16:36.038770       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Log level read as "", defaulting to INFO. To change, set LOG_LEVEL environment variable to WARN, ERROR, or DEBUG.
I0417 21:16:36.039028       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Build up list of existing ingresses
I0417 21:16:36.041806       1 elbv2.go:43] Request: elasticloadbalancing/&{DescribeLoadBalancers POST / %!s(*request.Paginator=&{[Marker] [NextMarker]  }) %!s(func(*request.Request) error=<nil>)}, Payload: {
  PageSize: 100
}
I0417 21:16:36.156689       1 elbv2.go:43] Request: elasticloadbalancing/&{DescribeTags POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  ResourceArns: ["arn:aws:elasticloadbalancing:us-east-2:account-id:loadbalancer/app/tectonic-831d927098db84e/6fab3e78b7c91aef"]
}
I0417 21:16:36.198328       1 route53.go:52] Request: route53/&{ListHostedZonesByName GET /2013-04-01/hostedzonesbyname %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  DNSName: "my-hosted-zone"
}
**I0417 21:16:36.360550       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Failed to resolve 2048.my-hosted-zone zoneID. Returned error Error calling route53.ListHostedZonesByName: AccessDenied**
I0417 21:16:36.360565       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Assembled 0 ingresses from existing AWS resources
I0417 21:16:36.360646       1 launch.go:96] &{ALB Ingress Controller 0.0.1 git-00000000 git://github.com/coreos/alb-ingress-controller}
I0417 21:16:36.360662       1 launch.go:99] Watching for ingress class: alb
I0417 21:16:36.360935       1 launch.go:232] Creating API server client for https://10.3.0.1:443
I0417 21:16:36.373465       1 launch.go:115] validated kube-system/default-http-backend as the default backend
I0417 21:16:36.382128       1 log.go:48] [ALB-INGRESS] [controller] [INFO]: Ingress class set to alb
I0417 21:16:36.382143       1 controller.go:1071] starting Ingress controller
I0417 21:16:36.389089       1 event.go:217] Event(api.ObjectReference{Kind:"Ingress", Namespace:"2048-game", Name:"2048-alb-ingress", UID:"569d7123-23a7-11e7-9698-06c1e8830d57", APIVersion:"extensions", ResourceVersion:"917772", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress 2048-game/2048-alb-ingress
I0417 21:16:36.389110       1 event.go:217] Event(api.ObjectReference{Kind:"Ingress", Namespace:"tectonic-system", Name:"tectonic-ingress", UID:"5758a03c-206a-11e7-9698-06c1e8830d57", APIVersion:"extensions", ResourceVersion:"262317", FieldPath:""}): type: 'Normal' reason: 'CREATE' Ingress tectonic-system/tectonic-ingress
I0417 21:16:36.401370       1 leaderelection.go:188] sucessfully acquired lease kube-system/ingress-controller-leader
W0417 21:16:37.389556       1 queue.go:87] requeuing tectonic-system/tectonic-ingress, err deferring sync till endpoints controller has synced
W0417 21:16:37.396584       1 queue.go:87] requeuing tectonic-system/tectonic-license, err deferring sync till endpoints controller has synced
I0417 21:16:46.698697       1 ec2.go:36] Request: ec2/&{DescribeSubnets POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  SubnetIds: ["subnet-40c35329","subnet-6066be1b","subnet-dd23d590"]
}
I0417 21:16:46.847916       1 ec2.go:36] Request: ec2/&{DescribeSecurityGroups POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  GroupIds: ["sg-28a2d841"]
}
I0417 21:16:46.904063       1 route53.go:52] Request: route53/&{ListHostedZonesByName GET /2013-04-01/hostedzonesbyname %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  DNSName: "my-hosted-zone"
}
I0417 21:16:46.976519       1 log.go:62] [ALB-INGRESS] [2048-game-2048-alb-ingress] [ERROR]: Unabled to locate ZoneId for %!s(*string=0xc42054def0).
I0417 21:16:46.976537       1 log.go:48] [ALB-INGRESS] [2048-game-2048-alb-ingress] [INFO]: Start ELBV2 (ALB) creation.
I0417 21:16:46.976727       1 elbv2.go:43] Request: elasticloadbalancing/&{CreateLoadBalancer POST / %!s(*request.Paginator=<nil>) %!s(func(*request.Request) error=<nil>)}, Payload: {
  Name: "tectonic-831d927098db84e",
  Scheme: "internet-facing",
  SecurityGroups: ["sg-28a2d841"],
  Subnets: ["subnet-40c35329","subnet-6066be1b","subnet-dd23d590"],
  Tags: [{
      Key: "Namespace",
      Value: "2048-game"
    },{
      Key: "IngressName",
      Value: "2048-alb-ingress"
    },{
      Key: "Hostname",
      Value: "2048.my-hosted-zone"
    }]
}
I0417 21:16:47.390498       1 log.go:48] [ALB-INGRESS] [2048-game-2048-alb-ingress] [INFO]: Completed ELBV2 (ALB) creation. Name: tectonic-831d927098db84e | ARN: arn:aws:elasticloadbalancing:us-east-2:<account-id>:loadbalancer/app/tectonic-831d927098db84e/6fab3e78b7c91aef
E0417 21:16:47.390625       1 runtime.go:64] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:70
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:63
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:49
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:514
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:63
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/signal_unix.go:290
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:55
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:24
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52
/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49
/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/asm_amd64.s:2197
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1525466]

goroutine 111 [running]:
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/runtime/runtime.go:56 +0x126
panic(0x17802c0, 0x254eb40)
	/home/travis/.gimme/versions/go1.8.linux.amd64/src/runtime/panic.go:489 +0x2cf
github.com/coreos/alb-ingress-controller/controller/alb.(*ResourceRecordSet).SyncState(0x0, 0xc4208212c0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/resourcerecordset.go:55 +0x26
github.com/coreos/alb-ingress-controller/controller/alb.LoadBalancers.SyncState(0xc42012a408, 0x1, 0x1, 0xc420128140, 0x3ff0000000000000, 0x2503040)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/alb/loadbalancers.go:24 +0xa0
github.com/coreos/alb-ingress-controller/controller.(*ALBIngress).SyncState(0xc420641a90)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/ingress.go:344 +0x81
github.com/coreos/alb-ingress-controller/controller.(*ALBController).Reload(0xc420168a20, 0x2583680, 0x0, 0x0, 0xc42056d790, 0x2, 0x2, 0x2583680, 0x0, 0x0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/controller/controller.go:107 +0x76
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).sync(0xc4201c5200, 0x169d0e0, 0xc42056d4a0, 0xc42056d4a0, 0xc42056d400)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:432 +0x626
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.(*GenericController).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.sync)-fm(0x169d0e0, 0xc42056d4a0, 0xa, 0xc4206fee00)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:158 +0x3e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).worker(0xc4204e53b0)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:86 +0xef
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).(github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.worker)-fm()
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x2a
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil.func1(0xc42075cfa8)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:96 +0x5e
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.JitterUntil(0xc42050bfa8, 0x12a05f200, 0x0, 0x1, 0xc42072f020)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:97 +0xad
github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait.Until(0xc42075cfa8, 0x12a05f200, 0xc42072f020)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/kubernetes/pkg/util/wait/wait.go:52 +0x4d
github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task.(*Queue).Run(0xc4204e53b0, 0x12a05f200, 0xc42072f020)
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/task/queue.go:49 +0x5e
created by github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller.GenericController.Start
	/home/travis/gopath/src/github.com/coreos/alb-ingress-controller/vendor/k8s.io/ingress/core/pkg/ingress/controller/controller.go:1081 +0x1f1

**Comment by bchav** [comment]
Figured this out- worker nodes need the same IAM policies as the controllers (duh).

**Comment by joshrosso** [comment]
Right, contingent on where the alb-ingress-controller lands.

Technically you could ensure it drops on the controller using a `nodeSelector`.

Nonetheless this identifies an issue where we need to ensure downstream syncs don't continue when we identify an issue with access rights.

**Comment by joshrosso** [comment]
Closing this one out too.

We my circle back on certain concerns such as 'should the controller attempt to reconcile in condition _Y_, but the panics, ref'd in this ticket, should be resolved.
