### ISSUE TITLE
Can't create DNS entry with three-part domain name

### ISSUE THREAD

**Issue by igorcanadi** [coreos/alb-ingress-controller#62]
Hi, thanks for the great product, it's exact what we need and are planning to use it in production.

However, after running it the first time, I got a panic similar to #61. It seems that the issue is in this line: https://github.com/coreos/alb-ingress-controller/blob/master/awsutil/route53.go#L73

getDomain() assumes that the last two components of a hostname is the domain. However, we are playing around in our sandbox AWS account, which owns *.dev.rockset.io and doesn't own *.rockset.io. This causes a failure in `awsutil.Route53svc.GetZoneID` because it's called with rockset.io instead of dev.rockset.io.

**Comment by joshrosso** [comment]
Hi @igorcanadi,

This naive assumption that the subdomain would be the first element prefixed by `.` [was only meant to be temporary](https://github.com/coreos/alb-ingress-controller/blob/b235fc86cd7738be29881594770d5062622fc3ae/awsutil/route53.go#L62-L65).

I'm thinking we implement a system where it the controller attempts to resolve a hosted zone by incrementally adding domains to its look up.

Consider the similar scenario where we need to satisfy `shop.site1.dev.rockset.io`.

1. Attempts and fails to resolve `site1.dev.rockset.io`
1. Attempts and fails to resolve `dev.rockset.io`
1. Attempts and succeeds to resolve `rockset.io`
    1. Sets `shop.site1.dev` as the resource record set in hosted zone `rockset.io`.

Does this flow make sense to you?

@bigkraig Thoughts?

**Comment by igorcanadi** [comment]
@joshrosso, your proposal makes sense and would work great for my use case.

**Comment by bigkraig** [comment]
Sounds good to me. I was also thinking we should make it an annotation incase you need to pick a specific zone

**Comment by igorcanadi** [comment]
Thanks @joshrosso !
