### ISSUE TITLE
Determine ALB subnets based on tags if annotation is not provided

### ISSUE THREAD

**Issue by mgoodness** [coreos/alb-ingress-controller#7]
If `alb.ingress.kubernetes.io/subnets` is not specified, we should use/emulate the existing cloudprovider functionality to determine the correct subnets in which to create the ALB. Specifically, internal ALBs will be created in subnets tagged with `kubernetes.io/role/internal-elb`, while internet-facing ones will be created in `kubernetes.io/role/elb` subnets.

**Comment by joshrosso** [comment]
I'm going to add this to 1.0...it'll make our examples much easier.

**Comment by joshrosso** [comment]
This has been implemented in https://github.com/coreos/alb-ingress-controller/commit/2964d75e3cef759c94b2328e54bedaf671e987c4 but does require 2 tags to qualify as a usable subnet.

From the commit:

```
 
      - kubernetes.io/cluster/$CLUSTER_NAME where $CLUSTER_NAME is the same
    cluster name specified on the ingress controller. The value of this tag
    must be 'shared'.
    
      - kubernetes.io/role/alb-ingress the value of this tag should be
    empty.
```
