### ISSUE TITLE
Add Support for Route53 Delegated Zones

### ISSUE THREAD

**Issue by jcderr** [coreos/alb-ingress-controller#83]
We use delegated zones for each "stack" of our software. However, the alb-ingress-controller does not respect these.

We might have, for instance:

      - host: auth.some-env.some-corp.com

Currently, it will make an `auth.some-env` record in the `some-corp.com` zone, even if the `some-env.some-corp.com` zone exists. Instead, it should make the record in the delegated zone.

**Comment by jcderr** [comment]
Would it be preferred to have an annotation (`alb.ingress.kubernetes.io/route53-zone`?) to control this?

**Comment by joshrosso** [comment]
Hi @jcderr 

That would certainly be a possibly. Have you used https://github.com/kubernetes-incubator/external-dns mentioned in #9 by chance?

Based on suggestions and this controller's primary use, it seems decoupling route 53 out of this controller altogether is a good move.

In other words, does the aforementioned project handle delegated zones the way you require?

**Comment by jcderr** [comment]
`external-dns` looks like a winner.
