### ISSUE TITLE
AWS doesn't allow you to add terminated EC2 instances to a TargetGroup

### ISSUE THREAD

**Issue by bigkraig** [coreos/alb-ingress-controller#87]
```
[ERROR]: InvalidTarget: The following targets are not in a running state and cannot be registered: 'i-0b75b61b1fe6ea77d', 'i-07bfeb82b48634b6b'
```

I was able to produce this by adding a worker and removing a worker at the same time. The added worker creates a new node in `GetNodes()`, triggering a modification of the TG. However, AWS sees that the removed worked is now terminated and throws the error above.

**Comment by joshrosso** [comment]
Seems with the NodeList storelister we no longer experience this issue.
