### ISSUE TITLE
alb-ingress-controller conflicts with dns-controller deployed by kops 1.6-beta.1

### ISSUE THREAD

**Issue by tavisma** [coreos/alb-ingress-controller#88]
The latest dns-controller deployed by default in the latest kops beta now watches ingress services and gets into a dns management battle with alb-ingress-controller

This causes both dns-controller and alb-ingress-controller pods to continually segfault

**Comment by tavispaquette** [comment]
As a workaround you can modify the dns-controller deployment and add a, "--watch-ingress=false" argument to the command which causes the dns-controller to behave as it previously did and ignore ingress services

**Comment by joshrosso** [comment]
Another reason to bail on native Route53 integration.

Intention to bail at #9.
Will be taken care of as part of #11 (see proposal).

**Comment by hjacobs** [comment]
Just FYI (already mentioned in #9): the plan is to replace the kops dns-controller with [external-dns](https://github.com/kubernetes-incubator/external-dns) (External DNS is a joint effort to consolidate the different DNS/Route53 controllers out there).

**Comment by tavispaquette** [comment]
fyi, kops-1.6 reverted their change
Their dns controller now ships with "--watch-ingress=false" set by default

**Comment by bigkraig** [comment]
We now have support for disabling route53.
