### ISSUE TITLE
Code will fail quietly if there is a `-` in cluster name

### ISSUE THREAD

**Issue by cmaloney** [coreos/alb-ingress-controller#98]
The code to describe load balancers (https://github.com/coreos/alb-ingress-controller/blob/master/awsutil/elbv2.go#L230) explicitly splits on `-`, expecting that to be first found after the cluster name. This makes it so that when the controller scans for existing load balancers, if the cluster name has a `-` in them none are found even if they were made by the alb ingress controller.

Could update the code to not do the split (And instead just chop the prefix + `-` off the end. Or could teach the `os.Getenv('CLUSTER_NAME')` to validate that CLUSTER_NAME doesn't contain `-`. Which would be preferred?

**Comment by bigkraig** [comment]
Fixed in master
